In [1]:
import pybullet as p
import pybullet_data
import time
import math
import numpy as np
from pinocchio_template import thneed
import sys
sys.path.append('/Users/emreadabag/code/sqpcpu/build')
import pysqpcpu

# Connect to the physics server
physicsClient = p.connect(p.GUI)
p.resetDebugVisualizerCamera(cameraDistance=2.0, cameraYaw=0, cameraPitch=-30, cameraTargetPosition=[0,0,0])

pybullet build time: Mar 13 2025 15:41:55


Version = 4.1 Metal - 88.1
Vendor = Apple
Renderer = Apple M3
b3Printf: Selected demo: Physics Server
startThreads creating 1 threads.
starting thread 0
started thread 0 
MotionThreadFunc thread started


In [14]:
friction_thing_N = 0
gravity = True
position_control = False
disable_velocity_control = not position_control

p.resetSimulation()


# Set up the environment
p.setAdditionalSearchPath(pybullet_data.getDataPath())
p.setGravity(0, 0, -9.81*gravity)
# planeId = p.loadURDF("/home/a2rlab/Documents/bullet3/data/plane.urdf")

# robotId = p.loadURDF("/home/a2rlab/Documents/bullet3/examples/pybullet/gym/pybullet_data/franka_panda/panda.urdf", [0, 0, 0], useFixedBase=1)
robotId = p.loadURDF("/Users/emreadabag/code/indy-ros2/indy_description/urdf_files/indy7.urdf", [0, 0, 0], useFixedBase=1, flags=p.URDF_USE_INERTIA_FROM_FILE)

num_joints = p.getNumJoints(robotId)
print(f"Number of joints: {num_joints}")

# Print joint info
for i in range(num_joints):
    joint_info = p.getJointInfo(robotId, i)
    print(f"Joint {i}, Name: {joint_info[1].decode('utf-8')}, Type: {joint_info[2]}")

if disable_velocity_control:
    p.setJointMotorControlArray(bodyIndex=robotId,
                            jointIndices=[i for i in range(num_joints)],
                            controlMode=p.VELOCITY_CONTROL,
                            forces=friction_thing_N*np.ones(num_joints))

sim_timestep = 0.005
solve_timestep = 0.01
p.setTimeStep(sim_timestep) # Default is 1/240 seconds
p.setRealTimeSimulation(False)

stockt = thneed(dt=solve_timestep, max_qp_iters=5)
t = pysqpcpu.Thneed(urdf_filename="/Users/emreadabag/code/indy-ros2/indy_description/urdf_files/indy7.urdf", N=32, dt=0.01, max_qp_iters=5)
if not gravity:
    t.gravity_off()

xs = 0 * np.hstack([np.ones(6), np.zeros(6)])
for i in range(1,7):
    p.resetJointState(robotId, i, xs[i-1], 0)

goal = stockt.eepos(0.8 * np.ones(6))
start = stockt.eepos(xs[:t.nq])

goal_trace = []
tracelen = 330
for i in range(tracelen):
    goal_trace.append((1/tracelen)*((tracelen - i)*start + (i)*goal)) # linear interpolation
    # goal_trace.append(goal)
goal_trace = np.array(goal_trace).reshape(-1)

all_xs = []
all_ctrl = []

running_fails = 0
successes = 0
for i in range(300):
    all_xs.append(np.array(xs))
    print(np.linalg.norm(stockt.eepos(xs[:6]) - goal_trace[3*(i+stockt.N-1):3*(i+stockt.N)]))
    

    # if np.linalg.norm(t.eepos(xs[:6]) - goal) < 5e-2:
    #     break

    # t.clean_start()
    # t.shift_start()
    
    # t.XU[:t.nx] = xs  # set start state, this helps with finding good min
    t.setxs(xs)

    if t.sqp(xs, goal_trace[3*i:3*(i+t.N)]):
        print("FAIL")
        running_fails +=1
        if running_fails==t.N-1:
            raise Exception(f"ran out of traj, successes: {successes}")
    else:
        successes +=1
        running_fails = 0
    
    if position_control and 0:
        o = 1
        p.setJointMotorControlArray(bodyIndex=robotId,
                                    jointIndices=[i for i in range(1,7)],
                                    controlMode=p.POSITION_CONTROL,
                                    targetPositions=t.XU[o*(t.nx+t.nu):o*(t.nx+t.nu)+t.nq], # + 0.3 * np.random.rand(6),
                                    # targetVelocities=t.XU[o*(t.nx+t.nu)+t.nq:o*(t.nx+t.nu)+t.nx],
                                    forces=[1e5 for _ in range(6)]
                                    )
    else:
        o = 0
        trqs = t.XU[o*(t.nx+t.nu)+t.nx:o*(t.nx+t.nu)+(t.nx+t.nu)]
        all_ctrl.append(trqs)
        p.setJointMotorControlArray(bodyIndex=robotId,
                                jointIndices=[i for i in range(1,7)],
                                controlMode=p.TORQUE_CONTROL,
                                forces=trqs)
        print(trqs)
    
    
    # Step the simulation forward
    for i in range(int(solve_timestep / sim_timestep)):
        p.stepSimulation()
        time.sleep(sim_timestep)
    

    joint_states = p.getJointStates(robotId, [i for i in range(1,7)])
    q = [j[0] for j in joint_states]
    v = [j[1] for j in joint_states]
    torques_applied = [j[3] for j in joint_states] # this is zeroed for torque control


    xs[:t.nq] = q
    xs[t.nq:t.nx] = v


# Disconnect from the physics server
# p.disconnect()

b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frame
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: tcp
Number of joints: 8
Joint 0, Name: global, Type: 4
Joint 1, Name: joint0, Type: 0
Joint 2, Name: joint1, Type: 0
Joint 3, Name: joint2, Type: 0
Joint 4, Name: joint3, Type: 0
Joint 5, Name: joint4, Type: 0
Joint 6, Name: joint5, Type: 0
Joint 7, Name: tcp, Type: 4
0.08532813130293432
[ 1.39747913e-01  1.23525181e+01  6.64304078e+00 -1.41939495e+00  1.30607702e+00  1.03398337e-03]
0.0880383144081753
[ 1.30645056e+00  6.22542771e+00  3.44017565e+00 -4.75151121e-01  7.98956062e-01  4.02403015e-03]
0.0907320042690889
[-3.43837463e-01  1.14535139e+01  5.66203292e+00 -1.18104913e+00  1.32799948e+00  3.79470024e-03]
0.09338987259584781
[ 0.64488233  6.04450857  2.90297902 -0.38685648  0.87229997  0.006076

KeyboardInterrupt: 

In [ ]:
all_xs = np.array(all_xs)
all_ctrl = np.array(all_ctrl)

In [ ]:
np.save('xs.npy', all_xs)
np.save('ctrl.npy', all_ctrl)

In [17]:
friction_thing_N = 0
gravity = True
position_control = False
disable_velocity_control = not position_control

p.resetSimulation()


# Set up the environment
p.setAdditionalSearchPath(pybullet_data.getDataPath())
p.setGravity(0, 0, -9.81*gravity)
# planeId = p.loadURDF("/home/a2rlab/Documents/bullet3/data/plane.urdf")

robotId = p.loadURDF("/Users/emreadabag/code/indy-ros2/indy_description/urdf_files/indy7.urdf", [0, 0, 0], useFixedBase=1, flags=p.URDF_USE_INERTIA_FROM_FILE)

num_joints = p.getNumJoints(robotId)
print(f"Number of joints: {num_joints}")

# Print joint info
for i in range(num_joints):
    joint_info = p.getJointInfo(robotId, i)
    print(f"Joint {i}, Name: {joint_info[1].decode('utf-8')}, Type: {joint_info[2]}")

if disable_velocity_control:
    p.setJointMotorControlArray(bodyIndex=robotId,
                            jointIndices=[i for i in range(num_joints)],
                            controlMode=p.VELOCITY_CONTROL,
                            forces=friction_thing_N*np.ones(num_joints))

sim_timestep = 0.01
solve_timestep = 0.01
p.setTimeStep(sim_timestep) # Default is 1/240 seconds

stockt = thneed(dt=solve_timestep, max_qp_iters=5)
t = pysqpcpu.Thneed(urdf_filename="/Users/emreadabag/code/indy-ros2/indy_description/urdf_files/indy7.urdf", N=32, dt=0.01, max_qp_iters=5)
if not gravity:
    t.gravity_off()

xs = 0 * np.hstack([np.ones(6), np.zeros(6)])
for i in range(1,7):
    p.resetJointState(robotId, i, xs[i-1], 0)

goal = stockt.eepos(0.8 * np.ones(6))
start = stockt.eepos(xs[:t.nq])

goal_trace = []
tracelen = 330
for i in range(tracelen):
    goal_trace.append((1/tracelen)*((tracelen - i)*start + (i)*goal)) # linear interpolation
    # goal_trace.append(goal)
goal_trace = np.array(goal_trace).reshape(-1)

all_xs = []
all_ctrl = []

running_fails = 0
successes = 0
t.sqp(xs, goal_trace[:3*t.N])
p.setRealTimeSimulation(True)
jointindices = [i for i in range(1,7)]
for i in range(300):
    s = time.time()
    # all_xs.append(np.array(xs))
    # print(np.linalg.norm(stockt.eepos(xs[:6]) - goal_trace[3*(i+stockt.N-1):3*(i+stockt.N)]))
    

    t.setxs(xs)

    if t.sqp(xs, goal_trace[3*i:3*(i+t.N)]):
        print("FAIL")
        running_fails +=1
        if running_fails==t.N-1:
            raise Exception(f"ran out of traj, successes: {successes}")
    else:
        successes +=1
        running_fails = 0
    
    if position_control and 0:
        o = 1
        p.setJointMotorControlArray(bodyIndex=robotId,
                                    jointIndices=jointindices,
                                    controlMode=p.POSITION_CONTROL,
                                    targetPositions=t.XU[o*(t.nx+t.nu):o*(t.nx+t.nu)+t.nq], # + 0.3 * np.random.rand(6),
                                    # targetVelocities=t.XU[o*(t.nx+t.nu)+t.nq:o*(t.nx+t.nu)+t.nx],
                                    forces=[1e5 for _ in range(6)]
                                    )
    else:
        o = 0
        trqs = t.XU[o*(t.nx+t.nu)+t.nx:o*(t.nx+t.nu)+(t.nx+t.nu)]
        # all_ctrl.append(trqs)
        p.setJointMotorControlArray(bodyIndex=robotId,
                                jointIndices=jointindices,
                                controlMode=p.TORQUE_CONTROL,
                                forces=trqs)    

    joint_states = p.getJointStates(robotId, jointindices)
    q = [j[0] for j in joint_states]
    v = [j[1] for j in joint_states]
    torques_applied = [j[3] for j in joint_states] # this is zeroed for torque control


    xs[:t.nq] = q
    xs[t.nq:t.nx] = v
    e = time.time()
    print(f"Simulation time: {1000*(e-s):.2f} ms")


# Disconnect from the physics server
# p.disconnect()

b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frame
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: tcp
Number of joints: 8
Joint 0, Name: global, Type: 4
Joint 1, Name: joint0, Type: 0
Joint 2, Name: joint1, Type: 0
Joint 3, Name: joint2, Type: 0
Joint 4, Name: joint3, Type: 0
Joint 5, Name: joint4, Type: 0
Joint 6, Name: joint5, Type: 0
Joint 7, Name: tcp, Type: 4
Simulation time: 81.43 ms
Simulation time: 123.85 ms
Simulation time: 78.08 ms
Simulation time: 77.49 ms
Simulation time: 82.49 ms
Simulation time: 83.79 ms
Simulation time: 87.38 ms
Simulation time: 86.73 ms
Simulation time: 85.64 ms
Simulation time: 87.71 ms
Simulation time: 83.28 ms
Simulation time: 86.32 ms
Simulation time: 86.68 ms
Simulation time: 87.74 ms
Simulation time: 84.48 ms
Simulation time: 84.88 ms
Simulation time: 85.10 ms

KeyboardInterrupt: 

: 

In [8]:
all_ctrl.min(axis=0) - all_ctrl.max(axis=0)

array([0., 0., 0., 0., 0., 0.])